------------------------------------------------------------------------ r20868 | aldot | 2008-01-17 22:47:59 +0100 (Thu, 17 Jan 2008) | 4 lines
- fix compilation:
  In file included from toolchain_build_i386/gcc-3.4.6/libiberty/hashtab.c:49:
  build_i386/staging_dir/i386-linux-uclibc/sys-include/malloc.h:193: error: ISO C forbids data definition with no type or storage class

[bernds: modified, since we had a local fix already]
------------------------------------------------------------------------


git-svn-id: svn://localhost/svn/toolchain/trunk@2467 2adf4935-75e9-4407-93b2-34b21a1880a4