add elf_machine_load_address() for Blackfin systems
The Blackfin port never defined elf_machine_load_address() because the one
place this code is called never matters to us.  But without it, common code
likes to hit a build failure, so stub it out.

ldso/ldso/dl-startup.c: In function '_dl_start':
ldso/ldso/dl-startup.c:170: warning: implicit declaration of function 'elf_machine_load_address'


git-svn-id: svn://localhost/svn/toolchain/trunk@3523 2adf4935-75e9-4407-93b2-34b21a1880a4